### ISSUE TITLE
build error : sed: can't read s@\( *\)case "$ngx_feature_run" in@\1adb push $NGX_AUTOTEST /data/local/tmp 2>\&1 >/dev/null\

### ISSUE THREAD

**Issue by Amos80** [tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android#1]
sed: can't read s@\( *\)case "$ngx_feature_run" in@\1adb push $NGX_AUTOTEST /data/local/tmp 2>\&1 >/dev/null\
&@: No such file or directory
sed: can't read s@\( *\)esac@&\
\1adb shell rm /data/local/tmp/$(basename $NGX_AUTOTEST)@: No such file or directory
sed: can't read s@/bin/sh -c $NGX_AUTOTEST@adb shell /data/local/tmp/$(basename $NGX_AUTOTEST)@: No such file or directory
sed: can't read s@`$NGX_AUTOTEST`@`adb shell /data/local/tmp/$(basename $NGX_AUTOTEST)`@: No such file or directory
sed: can't read s@ngx_test="$CC -o $NGX_AUTOTEST $NGX_AUTOTEST.c"@ngx_test="$CC $CC_AUX_FLAGS -o $NGX_AUTOTEST $NGX_AUTOTEST.c"@: No such file or directory
sed: can't read s@\( *\)ngx_size=`$NGX_AUTOTEST`@\1adb push $NGX_AUTOTEST /data/local/tmp 2>\&1 >/dev/null\
\1ngx_size=`adb shell /data/local/tmp/$(basename $NGX_AUTOTEST)`\
\1adb shell rm /data/local/tmp/$(basename $NGX_AUTOTEST)@: No such file or directory
sed: can't read s@\.openssl/@@: No such file or directory
sed: can't read s@UNIX_DEPS=.*@&\
src/os/unix/glob.h \\@: No such file or directory
sed: can't read s@UNIX_SRCS=.*@&\
src/os/unix/glob.c \\@: No such file or directory
sed: can't read s@#include <ngx_core.h>@&\
#include <openssl/des.h>@: No such file or directory
sed: can't read s@value = crypt((char \*) key, (char \*) salt);@value = DES_crypt((char \*) key, (char \*) salt);@: No such file or directory
building for android-arm
checking for C compiler ... not found

./configure: error: C compiler /gcc is not found

make: *** No rule to make target `build', needed by `default'.  Stop.
make: *** No rule to make target `install'.  Stop.

**Comment by Amos80** [comment]
why appear this question

**Comment by tatowilson** [comment]
I've updated the scripts and tested on Ubuntu 14.04.5 in VirtualBox.
Have a try with latest version 😃
