### ISSUE TITLE
Pcre support issue.

### ISSUE THREAD

**Issue by ctpxyza** [tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android#4]
[make_pcre.sh.txt](https://github.com/tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android/files/3075757/make_pcre.sh.txt)
[make_pcre.sh.txt](https://github.com/tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android/files/3075755/make_pcre.sh.txt)
**Info**
OS & Version:  ubuntu 18.04
Android NDK Version:  NDK-13b
Nginx Version:  1.14.2
OpenSSL Version: 1.1.1b
OpenSSL FIPS Version(if any): 2.0.16

**Describe the error**
Hi sir, I have built success without pcre according this script, but regex must be support in our project, so i enable pcre and built pcre OK. However I got error when i built nginx again.

**Log**
checking for int size ... CANNOT LINK EXECUTABLE: library "libgnustl_shared.so" not found
page record for 0xb6f3e01c was not found (block_size=16)

[make_pcre.log](https://github.com/tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android/files/3075751/make_pcre.log)
[make_nginx.sh.txt](https://github.com/tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android/files/3075754/make_nginx.sh.txt)
[make_pcre.sh.txt](https://github.com/tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android/files/3075758/make_pcre.sh.txt)

**Comment by tatowilson** [comment]
The error message said linker can't find the library `libgnustl_shared.so`. You may need to make sure it was in correct path.

BTW, it seems that you didn't compile `pcre` successfully according to `make_pcre.log` you attached.

**Comment by ctpxyza** [comment]
sorry about uploaded a error log, a new log will be given next Monday, thanks for your help.

**Comment by ctpxyza** [comment]
[make_nginx.log](https://github.com/tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android/files/3078613/make_nginx.log)   

> log of make nginx with pcre

[make_nginx.sh.txt](https://github.com/tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android/files/3078615/make_nginx.sh.txt)

> script of make nginx

[make_pcre.log](https://github.com/tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android/files/3078616/make_pcre.log)

> log of make pcre single.

[make_pcre.sh.txt](https://github.com/tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android/files/3078618/make_pcre.sh.txt)

> script of make pcre single.

[config.log.err.txt](https://github.com/tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android/files/3078669/config.log.err.txt)
> pcre config log when compiling with make_nginx.sh

[config.log.ok.txt](https://github.com/tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android/files/3078621/config.log.ok.txt)
> pcre config log when compiling with make_pcre.sh

[pcre.zip](https://github.com/tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android/files/3078623/pcre.zip)
> pcre source code and objs 

[Makefile.txt](https://github.com/tatowilson/Cross-Compile-Nginx-with-RTMP-Module-for-Android/files/3078649/Makefile.txt)
> Makefile of pcre at nginx-1.14.2/objs

**Comment by ctpxyza** [comment]
After reconfigure make_nginx.sh, previous error is ok, but a new problem occurs, it seems like "--host" can't   be transported to pcre's configure even if i changed "./configure --disable-shared $PCRE_CONF_OPT" in auto/lib/pcre/make  to "./configure --disable-shared  --host=arm-linux-androideabi $PCRE_CONF_OPT" or "export PCRE_CONF_OPT="--host=arm-linux-androideabi" in make_nginx.sh.   Makefile at nginx/objs still use "./configure --disable-shared" to compile pcre. 
Any suggestion for me?

**Comment by tatowilson** [comment]
Maybe you can have a try skipping compiling pcre during compiling nginx, and use the pcre library you built with `make_pcre.sh`.

**Comment by ctpxyza** [comment]
> Maybe you can have a try skipping compiling pcre during compiling nginx, and use the pcre library you built with `make_pcre.sh`.

OK，thank you, i will try it later.

**Comment by ctpxyza** [comment]
I have fixed it, thank you.
